version: '3'
services:
  server:
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./conf/:/app/conf/
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: omega
      POSTGRES_PASSWORD: omegapass
      POSTGRES_DB: omega
    ports:
      - 5432:5432
    volumes:
      - omega-db:/var/lib/postgresql/data

volumes:
  omega-db:
